@W-9142043 "self" functionality and base element refactoring
salesforce/utam-java pull request #36
Opened 2021-06-12 03:56 UTC by lizaiv77

2021-06-14 21:28 UTC, jimevanssfdc requested changes

2021-06-14 21:28 UTC, jimevanssfdc commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamMethodAction_Tests.java
> +    expectThrows(
We don't want to assert the right error is being thrown?

2021-06-14 21:28 UTC, jimevanssfdc commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamMethodAction_Tests.java
> +    expectThrows(
I think it's important when we're unit testing that a method throws an exception, that it's throwing the _right_ exception. Usually checking the message of the exception is good enough for this, but I know it's helped me track down several issues when refactoring.

2021-06-14 21:28 UTC, jimevanssfdc commented on utam-core/src/test/java/utam/core/framework/base/ContainerElementPageObjectTests.java
> +    assertThrows(pageObject::load);
Can we please move these to the Hamcrest matcher style (`expectThrows`, followed by `assertThat`), for consistency?

2021-06-14 23:25 UTC, lizaiv77 commented
@jimevanssfdc addressed comments, pls have another round. thx

2021-06-15 16:40 UTC, lizaiv77 commented
back to draft - discovered gap with nullable

2021-06-16 14:54 UTC, lizaiv77 commented
@jimevanssfdc ready for review when you get a chance

2021-06-16 16:28 UTC, jimevanssfdc approved these changes

2021-06-16 16:36 UTC, merged