@W-9745169 configurable guardrails
salesforce/utam-java pull request #59
Opened 2021-08-12 19:54 UTC by lizaiv77

- added guardrails mode to translator config
- refactored guardrails and moved to a separate package

2021-08-12 19:59 UTC, lizaiv77 commented
@jimevanssfdc ready for review

2021-08-16 21:18 UTC, jimevanssfdc requested changes

2021-08-16 21:18 UTC, jimevanssfdc commented on utam-core/src/main/java/utam/core/declarative/translator/GuardrailsMode.java
> +  warning,
Aren't enum values typically uppercase in Java?

2021-08-17 17:23 UTC, lizaiv77 commented
@jimevanssfdc addressed, pls feel free to merge if it's LGTM

2021-08-17 17:26 UTC, jimevans approved these changes

2021-08-17 17:28 UTC, jimevans approved these changes

2021-08-17 17:29 UTC, jimevans approved these changes

2021-08-17 17:30 UTC, jimevanssfdc approved these changes

2021-08-17 17:30 UTC, merged