@W-9806702 Allow UIScrollable class in Android UIAutomator locator
salesforce/utam-java pull request #66
Opened 2021-08-24 23:03 UTC by rajukamal

@helenren @lizaiv77 could you please review? This is required to use Android UIAutomator locator with 'UIScrollable' class to scroll to an element that is not in view.

2021-08-28 01:12 UTC, lizaiv77 commented on utam-core/src/main/java/utam/core/selenium/appium/LocatorUIAutomator.java
> +  public static final String UI_AUTOMATOR_SCROLLABLE_PREFIX = "new UiScrollable";
hm, what tests outside package?
it's been added in this PR and used in tests from same package. i actually tried to change access before asking

2021-08-28 01:12 UTC, lizaiv77 requested changes
same request - static variable should have package access

2021-08-30 21:32 UTC, rajukamal commented on utam-core/src/main/java/utam/core/selenium/appium/LocatorUIAutomator.java
> +  public static final String UI_AUTOMATOR_SCROLLABLE_PREFIX = "new UiScrollable";
we no longer are prepending the locator with new UiSelector() and won't need these constants anymore.

2021-08-30 21:39 UTC, rajukamal commented
@helenren @lizaiv77 Appium allows usage of Ui Automator locators without 'new UiSelector' prefix. So have removed the code to add the prefix. Now we support both formats - with and without prefix. 
Above change has been done in addition to the support for locators with prefix 'new UiScrollable' to scroll elements into view. 
Additionally, we now are supporting 'resourceIdMatches' method.

2021-08-31 18:01 UTC, helenren commented
LGTM. thanks. @rajukamal

2021-08-31 22:37 UTC, merged