root element type
salesforce/utam-java pull request #91
Opened 2021-11-12 07:08 UTC by lizaiv77

2021-11-12 18:25 UTC, lizaiv77 commented on utam-compiler/src/main/java/utam/compiler/helpers/BasicElementActionType.java
> -    }
removed this validation because we already made sure that element that gets basic action is basic earlier in the code

2021-11-12 18:38 UTC, lizaiv77 commented on utam-compiler/src/test/java/utam/compiler/grammar/TestUtilities.java
> -    }
those methods are no longer used in tests because tests were replaced by reading JSON file instead

2021-11-12 18:39 UTC, lizaiv77 commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamMethodActionApplyTests.java
> +  }
just some accidentally missed test coverage

2021-11-12 18:40 UTC, lizaiv77 commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamPageObject_DeserializeTests.java
> -    assertThat(rootElementNode.rootLocator, is(equalTo(LocatorBy.byCss("rootSelector"))));
added as test with Json

2021-11-12 18:40 UTC, lizaiv77 commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamPageObject_DeserializeTests.java
> -  }
added same tests in a different class

2021-11-12 18:41 UTC, lizaiv77 commented on utam-compiler/src/test/java/utam/compiler/grammar/UtamPageObject_Tests.java
> -  }
added same test in a different class

2021-11-15 18:28 UTC, jimevanssfdc requested changes
LGTM. Two little code formatting nits, which really could be ignored and fixed later. I'm okay if you want to push back on that.

2021-11-15 18:28 UTC, jimevanssfdc commented on utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java
> +      if(FRAME_ELEMENT_TYPE_NAME.equals(value)) {
Formatting nit: space after `if`

2021-11-15 18:28 UTC, jimevanssfdc commented on utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java
> +      if(TranslationTypesConfigJava.isPageObjectType(value)) {
Formatting nit: space after `if`

2021-11-15 18:33 UTC, lizaiv77 commented on utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java
> +      if(TranslationTypesConfigJava.isPageObjectType(value)) {
done

2021-11-15 18:33 UTC, lizaiv77 commented on utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java
> +      if(FRAME_ELEMENT_TYPE_NAME.equals(value)) {
done

2021-11-15 18:33 UTC, merged